dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "package-lock.json"

documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

logic:
  - changed-files:
      - any-glob-to-any-file: "app/**/*"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "__tests__/**/*"
          - "**/*.test.js"
          - "**/*.spec.js"
